noinst_PROGRAMS = ex_1 ex_2 ex_3 ex_4

# Common flags for all examples
AM_CPPFLAGS = -I$(top_srcdir)/include -I$(top_srcdir)/test
AM_LDFLAGS = -L$(top_builddir)/src
LDADD = $(top_builddir)/src/libsparsemap.la

# Example 1
ex_1_SOURCES = ex_1.c \
	$(top_srcdir)/test/common.c \
	$(top_srcdir)/test/common.h \
	$(top_srcdir)/test/munit.c \
	$(top_srcdir)/test/munit.h \
	$(top_srcdir)/test/qc.c \
	$(top_srcdir)/test/qc.h

ex_1_CFLAGS = $(AM_CFLAGS)

# Example 2
ex_2_SOURCES = ex_2.c \
	$(top_srcdir)/test/common.c \
	$(top_srcdir)/test/common.h \
	$(top_srcdir)/test/munit.c \
	$(top_srcdir)/test/munit.h \
	$(top_srcdir)/test/qc.c \
	$(top_srcdir)/test/qc.h

ex_2_CFLAGS = $(AM_CFLAGS)

# Example 3
ex_3_SOURCES = ex_3.c \
	$(top_srcdir)/test/common.c \
	$(top_srcdir)/test/common.h \
	$(top_srcdir)/test/munit.c \
	$(top_srcdir)/test/munit.h \
	$(top_srcdir)/test/qc.c \
	$(top_srcdir)/test/qc.h

ex_3_CFLAGS = $(AM_CFLAGS)

# Example 4
ex_4_SOURCES = ex_4.c \
	$(top_srcdir)/test/common.c \
	$(top_srcdir)/test/common.h \
	$(top_srcdir)/test/munit.c \
	$(top_srcdir)/test/munit.h \
	$(top_srcdir)/test/qc.c \
	$(top_srcdir)/test/qc.h

ex_4_CFLAGS = $(AM_CFLAGS)
