from collections.abc import Iterable, Iterator

class SparseMap:
    def __init__(self, items: Iterable[int] | None = None) -> None: ...
    def insert(self, idx: int) -> bool: ...
    def remove(self, idx: int) -> bool: ...
    def clear(self) -> None: ...
    def contains(self, idx: int) -> bool: ...
    def cardinality(self) -> int: ...
    def min(self) -> int | None: ...
    def max(self) -> int | None: ...
    def rank(self, idx: int) -> int: ...
    def select(self, n: int) -> int | None: ...
    def span(self, start: int, length: int, value: bool = True) -> int | None: ...
    def insert_range(self, start: int, end: int) -> None: ...
    def remove_range(self, start: int, end: int) -> None: ...
    def union(self, other: SparseMap) -> SparseMap: ...
    def intersection(self, other: SparseMap) -> SparseMap: ...
    def difference(self, other: SparseMap) -> SparseMap: ...
    def symmetric_difference(self, other: SparseMap) -> SparseMap: ...
    def intersects(self, other: SparseMap) -> bool: ...
    def is_subset(self, other: SparseMap) -> bool: ...
    def is_superset(self, other: SparseMap) -> bool: ...
    def shifted(self, offset: int) -> SparseMap: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> SparseMap: ...
    def __contains__(self, item: object) -> bool: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[int]: ...
    def __or__(self, other: SparseMap) -> SparseMap: ...
    def __and__(self, other: SparseMap) -> SparseMap: ...
    def __sub__(self, other: SparseMap) -> SparseMap: ...
    def __xor__(self, other: SparseMap) -> SparseMap: ...
    def __ior__(self, other: SparseMap) -> SparseMap: ...
    def __iand__(self, other: SparseMap) -> SparseMap: ...
    def __isub__(self, other: SparseMap) -> SparseMap: ...
    def __ixor__(self, other: SparseMap) -> SparseMap: ...
    def __repr__(self) -> str: ...

class SparseMapIter:
    def __iter__(self) -> SparseMapIter: ...
    def __next__(self) -> int: ...

__version__: str
