#!/bin/sh
# gen_api_index.sh -- regenerate the generated function index in docs/API.md.
#
# docs/API.md is hand-written prose (conventions, lifetime contract,
# worked examples) plus a complete index of the public API.  The prose is
# worth maintaining by hand; the index is not -- it fell two major
# versions behind and covered 27 of ~98 public identifiers.
#
# The index is extracted from sm.h, which is the actual source of truth:
# every public function is declared there with a Doxygen @brief.  The
# generated block lives between the markers below, so the prose around it
# is untouched.  scripts/check_api_index.sh (run in CI) fails if the
# committed block differs from what this script produces.
#
# Usage: scripts/gen_api_index.sh [--check]

set -eu

cd "$(dirname "$0")/.."

BEGIN='<!-- BEGIN GENERATED API INDEX -->'
END='<!-- END GENERATED API INDEX -->'

gen() {
	printf '%s\n' "$BEGIN"
	printf '<!-- Generated by scripts/gen_api_index.sh from sm.h.  Do not edit. -->\n\n'
	printf 'Every function, type and macro exported by `sm.h`, with its\n'
	printf 'one-line summary.  Signatures and full documentation live in the\n'
	printf 'header itself.\n\n'

	awk '
	# Collect the most recent @brief text so a declaration can claim it.
	/@brief/ {
		line = $0
		sub(/^.*@brief[ \t]*/, "", line)
		brief = line
		next
	}
	# A declaration: a line starting with a type and containing "sm_...(".
	/^[A-Za-z_][A-Za-z0-9_ *]*\**[ \t]*sm_[A-Za-z0-9_]*\(/ {
		decl = $0
		name = decl
		sub(/\(.*$/, "", name)          # drop the parameter list
		sub(/^.*[^A-Za-z0-9_]/, "", name)  # keep the identifier
		if (name ~ /^sm_/ && !(name in seen)) {
			seen[name] = 1
			# Trim a trailing period for table tidiness.
			b = brief
			sub(/[ \t]*$/, "", b)
			printf "| `%s()` | %s |\n", name, (b == "" ? "--" : b)
			brief = ""
		}
		next
	}
	' sm.h | sort -u > /tmp/.api_rows.$$

	printf '| Function | Summary |\n|----------|---------|\n'
	cat /tmp/.api_rows.$$
	rm -f /tmp/.api_rows.$$

	printf '\n### Types and macros\n\n'
	printf '| Name | Kind |\n|------|------|\n'
	{
		sed -n 's/^} \(sm_[A-Za-z0-9_]*\);.*/\1|type/p' sm.h
		sed -n 's/^typedef [^(]* \(sm_[A-Za-z0-9_]*\);.*/\1|type/p' sm.h
		sed -n 's/^#define \(SM_[A-Z0-9_]*\)[ \t(].*/\1|macro/p' sm.h
	} | sort -u | while IFS='|' read -r n k; do
		printf '| `%s` | %s |\n' "$n" "$k"
	done

	printf '\n%s\n' "$END"
}

if [ "${1:-}" = "--check" ]; then
	if ! grep -q "$BEGIN" docs/API.md; then
		echo "gen_api_index: marker missing from docs/API.md" >&2
		exit 1
	fi
	gen > /tmp/.api_new.$$
	sed -n "/$BEGIN/,/$END/p" docs/API.md > /tmp/.api_old.$$
	if cmp -s /tmp/.api_old.$$ /tmp/.api_new.$$; then
		rm -f /tmp/.api_old.$$ /tmp/.api_new.$$
		echo "gen_api_index: docs/API.md index is up to date"
		exit 0
	fi
	echo "ERROR: docs/API.md index is stale; run scripts/gen_api_index.sh" >&2
	diff -u /tmp/.api_old.$$ /tmp/.api_new.$$ | head -40 >&2 || true
	rm -f /tmp/.api_old.$$ /tmp/.api_new.$$
	exit 1
fi

if grep -q "$BEGIN" docs/API.md; then
	# Replace the existing block in place.
	awk -v b="$BEGIN" -v e="$END" '
		$0 == b { skip = 1; system("cat /tmp/.api_block") ; next }
		$0 == e { skip = 0; next }
		!skip
	' docs/API.md > /tmp/.api_out.$$ 2>/dev/null || true
	gen > /tmp/.api_block
	awk -v b="$BEGIN" -v e="$END" '
		$0 == b { skip = 1; while ((getline line < "/tmp/.api_block") > 0) print line; next }
		$0 == e { skip = 0; next }
		!skip
	' docs/API.md > /tmp/.api_out.$$
	mv /tmp/.api_out.$$ docs/API.md
	rm -f /tmp/.api_block
else
	# Append a fresh block.
	{ printf '\n## Complete API index\n\n'; gen; } >> docs/API.md
fi

echo "gen_api_index: docs/API.md index regenerated"
