.PHONY: doxygen man clean

doxygen:
	doxygen Doxyfile

man:
	@echo "Man pages live in ../man/"
	@echo "  sparsemap.3    -- API reference"
	@echo "  sparsemap.7    -- conceptual overview"

clean:
	rm -rf api/
